name: Build and Test

on:
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./test/ScreenSearch.Tests.Unit/ScreenSearch.Tests.Unit.csproj --configuration Release --no-build